CREATE TABLE dbo.DimProduct (
    ProductKey            INT IDENTITY(1,1) PRIMARY KEY,
    SKU                   VARCHAR(60)    NOT NULL UNIQUE,
    ProductName           VARCHAR(300)   NOT NULL,
    ModelNumber           VARCHAR(100)   NULL,
    UOM                   VARCHAR(20)    NULL,

    BusinessDivision      VARCHAR(20)    NULL,
    BusinessDivisionName  VARCHAR(200)   NULL,
    CategoryCode          VARCHAR(20)    NULL,
    CategoryName          VARCHAR(200)   NULL,
    segmentCode           VARCHAR(30)    NULL,
    segmentName           VARCHAR(200)   NULL,
    ProductCategoryCode   VARCHAR(40)    NULL,
    ProductCategoryName   VARCHAR(250)   NULL,

    LaunchYear            SMALLINT       NULL,
    TechnologyType        VARCHAR(100)   NULL,

    IsActive              BIT            NOT NULL DEFAULT (1),
    CreatedAt             DATETIME2      NOT NULL DEFAULT (SYSDATETIME())
);

INSERT INTO dbo.DimProduct (
    SKU, ProductName, ModelNumber, UOM,
    BusinessDivision, BusinessDivisionName,
    CategoryCode, CategoryName,
    segmentCode, segmentName,
    ProductCategoryCode, ProductCategoryName,
    LaunchYear, TechnologyType,
    IsActive
)
VALUES
('SKU-001', 'Smart LED TV 55"', 'MDL-342-28', 'PAIR', 'SPT', 'Sports & Outdoors', 'NET', 'Networking', 'SEG-G', 'Professional', 'PC-CAM', 'Digital Cameras', 2023, 'Wi-Fi 6', 1),
('SKU-002', 'Gaming Laptop Pro', 'MOD-556-74', 'PAIR', 'ACC', 'Accessories', 'DISP', 'Displays', 'SEG-B', 'Mid-Range', 'PC-RAM', 'Memory Modules', 2023, 'QLED', 1),
('SKU-003', 'USB-C Charging Hub', 'SKU-338-51', 'PK', 'HOM', 'Home Appliances', 'COMP', 'Computers', 'SEG-B', 'Mid-Range', 'PC-MON', 'Monitors', 2022, 'Wi-Fi 6', 1),
('SKU-004', 'Mechanical Keyboard TKL', 'SER-172-20', 'PK', 'IND', 'Industrial Equipment', 'INP', 'Input Devices', 'SEG-E', 'Enterprise', 'PC-LAPTOP', 'Portable Computers', 2020, 'Intel Core i9', 1),
('SKU-005', 'Curved Gaming Monitor 32"', 'SER-225-19', 'PK', 'OFF', 'Office Supplies', 'DISP', 'Displays', 'SEG-E', 'Enterprise', 'PC-SSD', 'Solid State Drives', 2022, 'Wi-Fi 6E', 1),
('SKU-006', '4K Webcam HD', 'PRD-478-92', 'BOX', 'SPT', 'Sports & Outdoors', 'PRINT', 'Printers', 'SEG-H', 'Consumer', 'PC-KB', 'Keyboards & Mice', 2022, 'Intel Core i9', 1),
('SKU-007', 'NVMe SSD 1TB', 'PRD-475-99', 'EA', 'MED', 'Medical Devices', 'CONN', 'Connectivity', 'SEG-E', 'Enterprise', 'PC-PRT', 'Printers & Scanners', 2020, '5G NR', 1),
('SKU-008', 'DDR5 RAM 32GB', 'TYP-190-96', 'SET', 'CE', 'Consumer Electronics', 'VID', 'Video', 'SEG-F', 'Budget', 'PC-GPU', 'Graphics Cards', 2022, 'Mini LED', 1),
('SKU-009', 'RTX Graphics Card', 'MDL-288-30', 'EA', 'IND', 'Industrial Equipment', 'DISP', 'Displays', 'SEG-B', 'Mid-Range', 'PC-GPU', 'Graphics Cards', 2021, 'RISC-V', 1),
('SKU-010', 'AMD Ryzen Processor', 'PRD-131-55', 'EA', 'IND', 'Industrial Equipment', 'NET', 'Networking', 'SEG-D', 'Peripherals', 'PC-MOB', 'Smartphones', 2024, 'OLED', 1),
('SKU-011', 'Intel Core CPU', 'SER-947-39', 'PAIR', 'SPT', 'Sports & Outdoors', 'CAM', 'Cameras', 'SEG-C', 'Gaming', 'PC-CAM', 'Digital Cameras', 2019, 'Apple M2', 1),
('SKU-012', 'Wireless Mouse Ergonomic', 'MOD-729-81', 'BOX', 'HOM', 'Home Appliances', 'AUD', 'Audio', 'SEG-E', 'Enterprise', 'PC-HUB', 'Hubs & Docking Stations', 2020, 'OLED', 0),
('SKU-013', 'RGB Gaming Headset', 'PRD-129-95', 'EA', 'OFF', 'Office Supplies', 'STR', 'Storage', 'SEG-G', 'Professional', 'PC-MOB', 'Smartphones', 2023, 'Bluetooth 5.0', 1),
('SKU-014', 'Portable SSD 2TB', 'MOD-153-11', 'SET', 'IND', 'Industrial Equipment', 'NET', 'Networking', 'SEG-F', 'Budget', 'PC-RAM', 'Memory Modules', 2023, 'Wi-Fi 6', 1),
('SKU-015', 'USB-C Docking Station', 'MDL-881-47', 'BOX', 'CE', 'Consumer Electronics', 'AUD', 'Audio', 'SEG-G', 'Professional', 'PC-SSD', 'Solid State Drives', 2023, 'USB-C PD', 1),
('SKU-016', 'True Wireless Earbuds', 'SER-936-73', 'SET', 'MED', 'Medical Devices', 'VID', 'Video', 'SEG-A', 'Premium', 'PC-MOB', 'Smartphones', 2020, 'Wi-Fi 6', 1),
('SKU-017', 'Smart Speaker Mini', 'MOD-814-60', 'BOX', 'MED', 'Medical Devices', 'INP', 'Input Devices', 'SEG-C', 'Gaming', 'PC-RAM', 'Memory Modules', 2018, 'DDR5', 1),
('SKU-018', 'Action Camera 4K', 'SKU-454-51', 'PK', 'IT', 'Information Technology', 'CAM', 'Cameras', 'SEG-H', 'Consumer', 'PC-CAM', 'Digital Cameras', 2021, 'HDMI 2.1', 0),
('SKU-019', 'Mirrorless Camera Kit', 'PRD-678-89', 'PK', 'CE', 'Consumer Electronics', 'PRINT', 'Printers', 'SEG-E', 'Enterprise', 'PC-CAM', 'Digital Cameras', 2018, 'Thunderbolt 4', 1),
('SKU-020', 'Laser Printer Multifunction', 'MDL-287-58', 'EA', 'HOM', 'Home Appliances', 'INP', 'Input Devices', 'SEG-H', 'Consumer', 'PC-SSD', 'Solid State Drives', 2024, 'PoE+', 1),
('SKU-021', 'Inkjet Photo Printer', 'PRD-917-57', 'PK', 'IND', 'Industrial Equipment', 'STR', 'Storage', 'SEG-A', 'Premium', 'PC-MOB', 'Smartphones', 2021, 'LTE Cat-20', 1),
('SKU-022', '27" 4K Monitor', 'SKU-942-96', 'BOX', 'IND', 'Industrial Equipment', 'VID', 'Video', 'SEG-B', 'Mid-Range', 'PC-CPU', 'Processors', 2024, 'USB-C PD', 1),
('SKU-023', 'Ultrawide Monitor 34"', 'SKU-992-14', 'SET', 'HOM', 'Home Appliances', 'NET', 'Networking', 'SEG-F', 'Budget', 'PC-AUDIO', 'Personal Audio Devices', 2023, 'Snapdragon 8 Gen 2', 1),
('SKU-024', 'Mechanical Gaming Keyboard', 'PRD-869-32', 'PAIR', 'OFF', 'Office Supplies', 'PWR', 'Power', 'SEG-F', 'Budget', 'PC-MON', 'Monitors', 2020, 'USB 3.2', 1),
('SKU-025', 'Gaming Mouse 16000 DPI', 'MDL-722-50', 'BOX', 'SPT', 'Sports & Outdoors', 'VID', 'Video', 'SEG-D', 'Peripherals', 'PC-PRT', 'Printers & Scanners', 2020, 'Mini LED', 1),
('SKU-026', 'Noise Cancelling Headphones', 'MDL-989-17', 'SET', 'CE', 'Consumer Electronics', 'CONN', 'Connectivity', 'SEG-A', 'Premium', 'PC-MOB', 'Smartphones', 2023, 'DDR5', 1),
('SKU-027', 'Soundbar 2.1 Channel', 'TYP-139-17', 'SET', 'MED', 'Medical Devices', 'CONN', 'Connectivity', 'SEG-H', 'Consumer', 'PC-CPU', 'Processors', 2020, 'Thunderbolt 4', 0),
('SKU-028', 'Network Switch 24-Port', 'TYP-282-20', 'EA', 'SPT', 'Sports & Outdoors', 'DISP', 'Displays', 'SEG-B', 'Mid-Range', 'PC-HDD', 'Hard Disk Drives', 2024, 'NVMe PCIe 4.0', 1),
('SKU-029', 'Wi-Fi 6 Router', 'PRD-488-41', 'PK', 'IT', 'Information Technology', 'STR', 'Storage', 'SEG-C', 'Gaming', 'PC-CPU', 'Processors', 2022, 'PoE+', 1),
('SKU-030', 'Power Bank 20000mAh', 'TYP-961-90', 'PK', 'ACC', 'Accessories', 'CONN', 'Connectivity', 'SEG-H', 'Consumer', 'PC-KB', 'Keyboards & Mice', 2024, 'HDMI 2.1', 1),
('SKU-031', 'Laptop Stand Adjustable', 'PRD-789-36', 'PAIR', 'HOM', 'Home Appliances', 'VID', 'Video', 'SEG-E', 'Enterprise', 'PC-LAPTOP', 'Portable Computers', 2022, '5G NR', 1),
('SKU-032', 'Monitor Arm Dual', 'SKU-585-29', 'BOX', 'ACC', 'Accessories', 'COMP', 'Computers', 'SEG-E', 'Enterprise', 'PC-HDD', 'Hard Disk Drives', 2021, 'Snapdragon 8 Gen 2', 1),
('SKU-033', 'Cable Management Kit', 'TYP-382-87', 'SET', 'CE', 'Consumer Electronics', 'STR', 'Storage', 'SEG-B', 'Mid-Range', 'PC-RAM', 'Memory Modules', 2019, 'Intel Core i9', 0),
('SKU-034', 'USB 3.2 Hub 7-Port', 'SER-384-31', 'SET', 'MED', 'Medical Devices', 'INP', 'Input Devices', 'SEG-D', 'Peripherals', 'PC-AUDIO', 'Personal Audio Devices', 2023, 'Wi-Fi 6', 1),
('SKU-035', 'Streaming Microphone', 'SER-849-59', 'BOX', 'HOM', 'Home Appliances', 'COMP', 'Computers', 'SEG-D', 'Peripherals', 'PC-MOB', 'Smartphones', 2020, 'Snapdragon 8 Gen 2', 1),
('SKU-036', 'Ring Light 18"', 'MOD-209-48', 'EA', 'IT', 'Information Technology', 'AUD', 'Audio', 'SEG-G', 'Professional', 'PC-MOB', 'Smartphones', 2020, 'Mini LED', 1),
('SKU-037', 'Green Screen Kit', 'TYP-536-38', 'EA', 'HOM', 'Home Appliances', 'CONN', 'Connectivity', 'SEG-F', 'Budget', 'PC-HDD', 'Hard Disk Drives', 2022, 'QLED', 1),
('SKU-038', 'Studio Monitor Speakers', 'MDL-351-58', 'EA', 'IND', 'Industrial Equipment', 'NET', 'Networking', 'SEG-E', 'Enterprise', 'PC-LAPTOP', 'Portable Computers', 2024, 'Mini LED', 1),
('SKU-039', 'Thunderbolt 4 Cable', 'SKU-324-14', 'EA', 'MED', 'Medical Devices', 'CONN', 'Connectivity', 'SEG-A', 'Premium', 'PC-HDD', 'Hard Disk Drives', 2023, 'NVMe PCIe 4.0', 1),
('SKU-040', 'HDMI 2.1 Cable 3m', 'SER-427-59', 'EA', 'CE', 'Consumer Electronics', 'CONN', 'Connectivity', 'SEG-E', 'Enterprise', 'PC-KB', 'Keyboards & Mice', 2019, 'PoE+', 1),
('SKU-041', 'DisplayPort Cable 1.4', 'SKU-722-13', 'BOX', 'ACC', 'Accessories', 'VID', 'Video', 'SEG-E', 'Enterprise', 'PC-RAM', 'Memory Modules', 2023, 'HDMI 2.1', 1),
('SKU-042', 'Ethernet Cable Cat8', 'MDL-368-11', 'SET', 'HOM', 'Home Appliances', 'AUD', 'Audio', 'SEG-D', 'Peripherals', 'PC-LAPTOP', 'Portable Computers', 2024, 'Bluetooth 5.0', 1),
('SKU-043', 'Smart Home Hub', 'SER-236-32', 'PAIR', 'HOM', 'Home Appliances', 'PRINT', 'Printers', 'SEG-A', 'Premium', 'PC-RAM', 'Memory Modules', 2018, 'Wi-Fi 6E', 1),
('SKU-044', 'Smart Plug 4-Pack', 'MOD-997-80', 'SET', 'IT', 'Information Technology', 'INP', 'Input Devices', 'SEG-D', 'Peripherals', 'PC-AUDIO', 'Personal Audio Devices', 2024, 'Intel Core i9', 0),
('SKU-045', 'IP Camera Outdoor', 'PRD-427-45', 'PAIR', 'SPT', 'Sports & Outdoors', 'MOB', 'Mobile Devices', 'SEG-A', 'Premium', 'PC-TAB', 'Tablets', 2019, 'RISC-V', 0),
('SKU-046', 'Video Doorbell Pro', 'TYP-831-79', 'EA', 'ACC', 'Accessories', 'DISP', 'Displays', 'SEG-F', 'Budget', 'PC-HUB', 'Hubs & Docking Stations', 2019, 'Mini LED', 1),
('SKU-047', 'Smart Thermostat', 'SKU-617-90', 'PAIR', 'HOM', 'Home Appliances', 'DISP', 'Displays', 'SEG-H', 'Consumer', 'PC-PRT', 'Printers & Scanners', 2018, 'LTE Cat-20', 1),
('SKU-048', 'Air Purifier HEPA', 'SER-335-15', 'PK', 'IND', 'Industrial Equipment', 'DISP', 'Displays', 'SEG-H', 'Consumer', 'PC-AUDIO', 'Personal Audio Devices', 2020, 'Bluetooth 5.0', 1),
('SKU-049', 'Robot Vacuum Pro', 'TYP-899-62', 'EA', 'HOM', 'Home Appliances', 'PWR', 'Power', 'SEG-G', 'Professional', 'PC-CAM', 'Digital Cameras', 2020, 'USB 3.2', 1),
('SKU-050', 'Smart Light Bulb Pack', 'TYP-375-43', 'SET', 'IT', 'Information Technology', 'CAM', 'Cameras', 'SEG-B', 'Mid-Range', 'PC-CPU', 'Processors', 2021, 'AMD Ryzen 9', 1),
('SKU-051', 'Wireless Charging Pad', 'SER-145-76', 'EA', 'HOM', 'Home Appliances', 'PWR', 'Power', 'SEG-F', 'Budget', 'PC-HDD', 'Hard Disk Drives', 2021, 'NVMe PCIe 4.0', 1),
('SKU-052', 'MagSafe Car Mount', 'MDL-489-85', 'PK', 'IND', 'Industrial Equipment', 'DISP', 'Displays', 'SEG-F', 'Budget', 'PC-GPU', 'Graphics Cards', 2022, 'AMD Ryzen 9', 1),
('SKU-053', 'Phone Stand Adjustable', 'SER-912-97', 'EA', 'OFF', 'Office Supplies', 'AUD', 'Audio', 'SEG-E', 'Enterprise', 'PC-CPU', 'Processors', 2020, 'Mini LED', 1),
('SKU-054', 'Screen Protector Premium', 'PRD-152-61', 'PK', 'CE', 'Consumer Electronics', 'PWR', 'Power', 'SEG-F', 'Budget', 'PC-SSD', 'Solid State Drives', 2021, 'Wi-Fi 6', 0),
('SKU-055', 'Laptop Sleeve 15"', 'TYP-109-38', 'SET', 'SPT', 'Sports & Outdoors', 'DISP', 'Displays', 'SEG-G', 'Professional', 'PC-MOB', 'Smartphones', 2023, '5G NR', 1),
('SKU-056', 'Backpack Tech 30L', 'MDL-638-46', 'SET', 'OFF', 'Office Supplies', 'AUD', 'Audio', 'SEG-G', 'Professional', 'PC-CAM', 'Digital Cameras', 2021, 'AMD Ryzen 9', 1),
('SKU-057', 'Cable Organizer Bag', 'SER-383-33', 'SET', 'MED', 'Medical Devices', 'AUD', 'Audio', 'SEG-D', 'Peripherals', 'PC-HUB', 'Hubs & Docking Stations', 2018, '5G NR', 1),
('SKU-058', 'Travel Adapter Universal', 'TYP-378-77', 'EA', 'HOM', 'Home Appliances', 'NET', 'Networking', 'SEG-B', 'Mid-Range', 'PC-CAM', 'Digital Cameras', 2020, 'QLED', 1),
('SKU-059', 'Gaming Chair Ergonomic', 'TYP-101-19', 'PAIR', 'SPT', 'Sports & Outdoors', 'COMP', 'Computers', 'SEG-H', 'Consumer', 'PC-MOB', 'Smartphones', 2018, 'OLED', 1),
('SKU-060', 'Monitor Riser Bamboo', 'TYP-956-95', 'BOX', 'HOM', 'Home Appliances', 'COMP', 'Computers', 'SEG-B', 'Mid-Range', 'PC-AUDIO', 'Personal Audio Devices', 2023, 'PoE+', 1),
('SKU-061', 'Desk Mat XL', 'SKU-348-77', 'EA', 'MED', 'Medical Devices', 'PWR', 'Power', 'SEG-E', 'Enterprise', 'PC-SSD', 'Solid State Drives', 2019, 'LTE Cat-20', 1),
('SKU-062', 'Wrist Rest Gel', 'MDL-279-33', 'PK', 'MED', 'Medical Devices', 'VID', 'Video', 'SEG-E', 'Enterprise', 'PC-TV', 'Television & Displays', 2018, 'Intel Core i9', 1),
('SKU-063', 'Portable Projector 1080p', 'SER-384-70', 'SET', 'OFF', 'Office Supplies', 'INP', 'Input Devices', 'SEG-H', 'Consumer', 'PC-HUB', 'Hubs & Docking Stations', 2020, 'AMD Ryzen 9', 1),
('SKU-064', 'Document Scanner Portable', 'PRD-445-83', 'SET', 'MED', 'Medical Devices', 'NET', 'Networking', 'SEG-C', 'Gaming', 'PC-AUDIO', 'Personal Audio Devices', 2022, 'MediaTek Dimensity', 0),
('SKU-065', 'Label Printer Wireless', 'MOD-507-51', 'PAIR', 'ACC', 'Accessories', 'CAM', 'Cameras', 'SEG-C', 'Gaming', 'PC-AUDIO', 'Personal Audio Devices', 2024, 'USB-C PD', 0),
('SKU-066', 'Barcode Scanner USB', 'SKU-744-47', 'BOX', 'ACC', 'Accessories', 'NET', 'Networking', 'SEG-D', 'Peripherals', 'PC-SSD', 'Solid State Drives', 2021, 'MediaTek Dimensity', 1),
('SKU-067', 'Drawing Tablet A4', 'MOD-127-55', 'BOX', 'HOM', 'Home Appliances', 'DISP', 'Displays', 'SEG-G', 'Professional', 'PC-HDD', 'Hard Disk Drives', 2024, 'MediaTek Dimensity', 1),
('SKU-068', 'Stylus Pen Active', 'SKU-693-80', 'PAIR', 'OFF', 'Office Supplies', 'CAM', 'Cameras', 'SEG-E', 'Enterprise', 'PC-HDD', 'Hard Disk Drives', 2019, 'MediaTek Dimensity', 1),
('SKU-069', 'VR Headset Standalone', 'PRD-944-81', 'EA', 'ACC', 'Accessories', 'CONN', 'Connectivity', 'SEG-A', 'Premium', 'PC-LAPTOP', 'Portable Computers', 2024, 'Wi-Fi 6', 1),
('SKU-070', 'Smart Glasses AR', 'TYP-189-55', 'PK', 'ACC', 'Accessories', 'DISP', 'Displays', 'SEG-D', 'Peripherals', 'PC-GPU', 'Graphics Cards', 2024, 'Wi-Fi 6E', 1),
('SKU-071', 'Fitness Tracker Pro', 'SER-781-84', 'SET', 'MED', 'Medical Devices', 'NET', 'Networking', 'SEG-A', 'Premium', 'PC-TAB', 'Tablets', 2021, 'LTE Cat-20', 1),
('SKU-072', 'Smartwatch Series 5', 'MOD-895-61', 'PK', 'MED', 'Medical Devices', 'CAM', 'Cameras', 'SEG-G', 'Professional', 'PC-HUB', 'Hubs & Docking Stations', 2024, 'NVMe PCIe 4.0', 1),
('SKU-073', 'Blood Pressure Monitor', 'MOD-961-35', 'PK', 'IT', 'Information Technology', 'AUD', 'Audio', 'SEG-E', 'Enterprise', 'PC-LAPTOP', 'Portable Computers', 2024, 'Wi-Fi 6E', 1),
('SKU-074', 'Digital Thermometer', 'SER-119-15', 'PK', 'CE', 'Consumer Electronics', 'VID', 'Video', 'SEG-D', 'Peripherals', 'PC-CAM', 'Digital Cameras', 2020, 'NVMe PCIe 4.0', 0),
('SKU-075', 'Mini PC Intel NUC', 'MDL-551-66', 'SET', 'IND', 'Industrial Equipment', 'INP', 'Input Devices', 'SEG-D', 'Peripherals', 'PC-RAM', 'Memory Modules', 2018, 'LTE Cat-20', 1),
('SKU-076', 'Raspberry Pi 4 Kit', 'MDL-930-97', 'SET', 'OFF', 'Office Supplies', 'DISP', 'Displays', 'SEG-E', 'Enterprise', 'PC-TAB', 'Tablets', 2019, 'Mini LED', 1),
('SKU-077', 'Arduino Starter Kit', 'SER-883-26', 'BOX', 'IT', 'Information Technology', 'CAM', 'Cameras', 'SEG-H', 'Consumer', 'PC-TAB', 'Tablets', 2021, 'DDR5', 1),
('SKU-078', 'Soldering Station Digital', 'SER-868-90', 'PK', 'MED', 'Medical Devices', 'MOB', 'Mobile Devices', 'SEG-C', 'Gaming', 'PC-HDD', 'Hard Disk Drives', 2018, 'Thunderbolt 4', 1),
('SKU-079', 'Oscilloscope Digital 2ch', 'SER-456-21', 'EA', 'OFF', 'Office Supplies', 'VID', 'Video', 'SEG-D', 'Peripherals', 'PC-AUDIO', 'Personal Audio Devices', 2022, 'Mini LED', 1),
('SKU-080', 'Bench Power Supply', 'PRD-243-15', 'EA', 'OFF', 'Office Supplies', 'PRINT', 'Printers', 'SEG-B', 'Mid-Range', 'PC-PRT', 'Printers & Scanners', 2018, 'Bluetooth 5.0', 1),
('SKU-081', 'Component Tester', 'PRD-157-38', 'BOX', 'ACC', 'Accessories', 'COMP', 'Computers', 'SEG-D', 'Peripherals', 'PC-GPU', 'Graphics Cards', 2023, 'MediaTek Dimensity', 1),
('SKU-082', 'PCB Holder', 'MOD-820-34', 'SET', 'CE', 'Consumer Electronics', 'MOB', 'Mobile Devices', 'SEG-B', 'Mid-Range', 'PC-MON', 'Monitors', 2023, 'Bluetooth 5.0', 1),
('SKU-083', 'Server Rack Cabinet 12U', 'SKU-414-78', 'PK', 'IT', 'Information Technology', 'VID', 'Video', 'SEG-F', 'Budget', 'PC-TAB', 'Tablets', 2020, '5G NR', 1),
('SKU-084', 'KVM Switch 4-Port', 'SKU-597-92', 'PAIR', 'SPT', 'Sports & Outdoors', 'NET', 'Networking', 'SEG-B', 'Mid-Range', 'PC-CPU', 'Processors', 2021, 'USB 3.2', 0),
('SKU-085', 'UPS Battery Backup', 'SKU-592-67', 'EA', 'CE', 'Consumer Electronics', 'MOB', 'Mobile Devices', 'SEG-E', 'Enterprise', 'PC-MON', 'Monitors', 2021, 'MediaTek Dimensity', 1),
('SKU-086', 'Rackmount PDU', 'TYP-136-81', 'EA', 'IND', 'Industrial Equipment', 'MOB', 'Mobile Devices', 'SEG-A', 'Premium', 'PC-KB', 'Keyboards & Mice', 2019, 'Snapdragon 8 Gen 2', 1),
('SKU-087', 'Fiber Patch Cable SM', 'MOD-174-71', 'EA', 'IT', 'Information Technology', 'CAM', 'Cameras', 'SEG-G', 'Professional', 'PC-LAPTOP', 'Portable Computers', 2024, 'ARM Cortex', 1),
('SKU-088', 'SFP+ Transceiver Module', 'SKU-887-15', 'PAIR', 'ACC', 'Accessories', 'MOB', 'Mobile Devices', 'SEG-E', 'Enterprise', 'PC-RAM', 'Memory Modules', 2023, 'ARM Cortex', 1),
('SKU-089', 'PoE Injector 30W', 'MDL-998-57', 'PAIR', 'ACC', 'Accessories', 'VID', 'Video', 'SEG-E', 'Enterprise', 'PC-SSD', 'Solid State Drives', 2023, 'Snapdragon 8 Gen 2', 1),
('SKU-090', 'Managed Switch 48-Port', 'MOD-141-27', 'SET', 'MED', 'Medical Devices', 'NET', 'Networking', 'SEG-B', 'Mid-Range', 'PC-MOB', 'Smartphones', 2023, 'Bluetooth 5.0', 1),
('SKU-091', 'Thermal Camera Handheld', 'SKU-722-50', 'PAIR', 'IT', 'Information Technology', 'COMP', 'Computers', 'SEG-C', 'Gaming', 'PC-KB', 'Keyboards & Mice', 2023, 'LTE Cat-20', 1),
('SKU-092', 'Endoscope Camera', 'PRD-772-52', 'BOX', 'OFF', 'Office Supplies', 'MOB', 'Mobile Devices', 'SEG-C', 'Gaming', 'PC-HUB', 'Hubs & Docking Stations', 2018, 'Thunderbolt 4', 1),
('SKU-093', 'Digital Microscope USB', 'MOD-134-31', 'SET', 'SPT', 'Sports & Outdoors', 'PRINT', 'Printers', 'SEG-F', 'Budget', 'PC-GPU', 'Graphics Cards', 2018, 'PoE+', 1),
('SKU-094', 'Caliper Digital 6"', 'TYP-510-50', 'SET', 'IT', 'Information Technology', 'STR', 'Storage', 'SEG-A', 'Premium', 'PC-TAB', 'Tablets', 2021, 'LTE Cat-20', 1),
('SKU-095', 'Label Maker Pro', 'SER-492-99', 'PK', 'IT', 'Information Technology', 'NET', 'Networking', 'SEG-C', 'Gaming', 'PC-RAM', 'Memory Modules', 2018, 'Apple M2', 1),
('SKU-096', 'Laminator A3', 'SER-530-55', 'PAIR', 'CE', 'Consumer Electronics', 'INP', 'Input Devices', 'SEG-F', 'Budget', 'PC-CPU', 'Processors', 2020, 'QLED', 1),
('SKU-097', 'Paper Shredder 12-Sheet', 'TYP-644-94', 'EA', 'MED', 'Medical Devices', 'PRINT', 'Printers', 'SEG-C', 'Gaming', 'PC-CAM', 'Digital Cameras', 2023, 'ARM Cortex', 1),
('SKU-098', 'Electric Stapler', 'TYP-705-92', 'PAIR', 'CE', 'Consumer Electronics', 'NET', 'Networking', 'SEG-D', 'Peripherals', 'PC-SSD', 'Solid State Drives', 2022, 'PoE+', 1),
('SKU-099', 'Wireless Bluetooth Headphones v2', 'MOD-835-82', 'BOX', 'SPT', 'Sports & Outdoors', 'CAM', 'Cameras', 'SEG-B', 'Mid-Range', 'PC-GPU', 'Graphics Cards', 2021, 'Mini LED', 1),
('SKU-100', 'Smart LED TV 55" v2', 'SKU-944-17', 'BOX', 'IT', 'Information Technology', 'AUD', 'Audio', 'SEG-C', 'Gaming', 'PC-MON', 'Monitors', 2023, 'DDR5', 1),
('SKU-101', 'Gaming Laptop Pro v2', 'MOD-730-46', 'PK', 'MED', 'Medical Devices', 'VID', 'Video', 'SEG-D', 'Peripherals', 'PC-TV', 'Television & Displays', 2024, 'USB-C PD', 0),
('SKU-102', 'USB-C Charging Hub v2', 'SER-868-34', 'BOX', 'ACC', 'Accessories', 'VID', 'Video', 'SEG-B', 'Mid-Range', 'PC-PRT', 'Printers & Scanners', 2023, 'Intel Core i9', 1),
('SKU-103', 'Mechanical Keyboard TKL v2', 'TYP-253-65', 'SET', 'CE', 'Consumer Electronics', 'CAM', 'Cameras', 'SEG-H', 'Consumer', 'PC-HDD', 'Hard Disk Drives', 2020, 'OLED', 1),
('SKU-104', 'Curved Gaming Monitor 32" v2', 'MOD-723-36', 'PAIR', 'MED', 'Medical Devices', 'COMP', 'Computers', 'SEG-A', 'Premium', 'PC-CPU', 'Processors', 2024, 'HDMI 2.1', 1),
('SKU-105', '4K Webcam HD v2', 'TYP-836-10', 'BOX', 'SPT', 'Sports & Outdoors', 'AUD', 'Audio', 'SEG-E', 'Enterprise', 'PC-CAM', 'Digital Cameras', 2021, 'Intel Core i9', 1),
('SKU-106', 'NVMe SSD 1TB v2', 'MDL-704-42', 'BOX', 'IND', 'Industrial Equipment', 'DISP', 'Displays', 'SEG-D', 'Peripherals', 'PC-GPU', 'Graphics Cards', 2024, 'Intel Core i9', 1),
('SKU-107', 'DDR5 RAM 32GB v2', 'SKU-176-70', 'BOX', 'OFF', 'Office Supplies', 'AUD', 'Audio', 'SEG-G', 'Professional', 'PC-HDD', 'Hard Disk Drives', 2024, 'OLED', 1),
('SKU-108', 'RTX Graphics Card v2', 'SER-934-69', 'PK', 'IT', 'Information Technology', 'AUD', 'Audio', 'SEG-H', 'Consumer', 'PC-MON', 'Monitors', 2019, 'HDMI 2.1', 1),
('SKU-109', 'AMD Ryzen Processor v2', 'SKU-937-40', 'SET', 'SPT', 'Sports & Outdoors', 'PWR', 'Power', 'SEG-A', 'Premium', 'PC-MON', 'Monitors', 2024, 'AMD Ryzen 9', 1),
('SKU-110', 'Intel Core CPU v2', 'SER-387-35', 'EA', 'IT', 'Information Technology', 'DISP', 'Displays', 'SEG-F', 'Budget', 'PC-KB', 'Keyboards & Mice', 2020, 'Wi-Fi 6', 1),
('SKU-111', 'Wireless Mouse Ergonomic v2', 'SKU-946-22', 'PK', 'IT', 'Information Technology', 'STR', 'Storage', 'SEG-A', 'Premium', 'PC-CPU', 'Processors', 2020, 'NVMe PCIe 4.0', 1),
('SKU-112', 'RGB Gaming Headset v2', 'MOD-127-13', 'BOX', 'OFF', 'Office Supplies', 'VID', 'Video', 'SEG-A', 'Premium', 'PC-MOB', 'Smartphones', 2024, 'RISC-V', 1),
('SKU-113', 'Portable SSD 2TB v2', 'MOD-688-95', 'PAIR', 'HOM', 'Home Appliances', 'PWR', 'Power', 'SEG-B', 'Mid-Range', 'PC-CPU', 'Processors', 2023, 'Wi-Fi 6', 1),
('SKU-114', 'USB-C Docking Station v2', 'SKU-513-68', 'PK', 'HOM', 'Home Appliances', 'PWR', 'Power', 'SEG-C', 'Gaming', 'PC-PRT', 'Printers & Scanners', 2023, 'NVMe PCIe 4.0', 1),
('SKU-115', 'True Wireless Earbuds v2', 'TYP-861-71', 'PK', 'SPT', 'Sports & Outdoors', 'PWR', 'Power', 'SEG-G', 'Professional', 'PC-SSD', 'Solid State Drives', 2020, 'Wi-Fi 6E', 1),
('SKU-116', 'Smart Speaker Mini v2', 'MDL-165-73', 'EA', 'MED', 'Medical Devices', 'VID', 'Video', 'SEG-E', 'Enterprise', 'PC-GPU', 'Graphics Cards', 2022, '5G NR', 1),
('SKU-117', 'Action Camera 4K v2', 'PRD-756-19', 'PAIR', 'OFF', 'Office Supplies', 'DISP', 'Displays', 'SEG-E', 'Enterprise', 'PC-TV', 'Television & Displays', 2021, 'NVMe PCIe 4.0', 1),
('SKU-118', 'Mirrorless Camera Kit v2', 'TYP-923-62', 'BOX', 'IT', 'Information Technology', 'PRINT', 'Printers', 'SEG-C', 'Gaming', 'PC-HUB', 'Hubs & Docking Stations', 2023, 'HDMI 2.1', 1),
('SKU-119', 'Laser Printer Multifunction v2', 'TYP-681-80', 'SET', 'CE', 'Consumer Electronics', 'STR', 'Storage', 'SEG-A', 'Premium', 'PC-HDD', 'Hard Disk Drives', 2020, 'Thunderbolt 4', 1),
('SKU-120', 'Inkjet Photo Printer v2', 'MOD-818-87', 'PK', 'HOM', 'Home Appliances', 'PWR', 'Power', 'SEG-F', 'Budget', 'PC-SSD', 'Solid State Drives', 2023, 'Wi-Fi 6E', 1),
('SKU-121', '27" 4K Monitor v2', 'TYP-173-75', 'PK', 'ACC', 'Accessories', 'AUD', 'Audio', 'SEG-E', 'Enterprise', 'PC-KB', 'Keyboards & Mice', 2020, 'PoE+', 1),
('SKU-122', 'Ultrawide Monitor 34" v2', 'MDL-524-37', 'BOX', 'ACC', 'Accessories', 'INP', 'Input Devices', 'SEG-D', 'Peripherals', 'PC-HUB', 'Hubs & Docking Stations', 2021, 'Mini LED', 1),
('SKU-123', 'Mechanical Gaming Keyboard v2', 'MOD-847-46', 'SET', 'CE', 'Consumer Electronics', 'MOB', 'Mobile Devices', 'SEG-B', 'Mid-Range', 'PC-MON', 'Monitors', 2018, 'RISC-V', 0),
('SKU-124', 'Gaming Mouse 16000 DPI v2', 'SKU-922-53', 'PK', 'HOM', 'Home Appliances', 'NET', 'Networking', 'SEG-G', 'Professional', 'PC-TV', 'Television & Displays', 2021, 'ARM Cortex', 1),
('SKU-125', 'Noise Cancelling Headphones v2', 'MDL-650-46', 'EA', 'IND', 'Industrial Equipment', 'STR', 'Storage', 'SEG-C', 'Gaming', 'PC-RAM', 'Memory Modules', 2024, 'Thunderbolt 4', 1),
('SKU-126', 'Soundbar 2.1 Channel v2', 'MDL-824-96', 'SET', 'ACC', 'Accessories', 'MOB', 'Mobile Devices', 'SEG-B', 'Mid-Range', 'PC-MOB', 'Smartphones', 2023, 'Bluetooth 5.0', 1),
('SKU-127', 'Network Switch 24-Port v2', 'TYP-835-52', 'SET', 'CE', 'Consumer Electronics', 'STR', 'Storage', 'SEG-B', 'Mid-Range', 'PC-RAM', 'Memory Modules', 2023, 'Mini LED', 0),
('SKU-128', 'Wi-Fi 6 Router v2', 'SKU-583-70', 'BOX', 'IT', 'Information Technology', 'STR', 'Storage', 'SEG-G', 'Professional', 'PC-TV', 'Television & Displays', 2022, 'Apple M2', 1),
('SKU-129', 'Power Bank 20000mAh v2', 'SER-403-90', 'BOX', 'SPT', 'Sports & Outdoors', 'VID', 'Video', 'SEG-B', 'Mid-Range', 'PC-GPU', 'Graphics Cards', 2022, 'OLED', 1),
('SKU-130', 'Laptop Stand Adjustable v2', 'MOD-762-93', 'PAIR', 'CE', 'Consumer Electronics', 'COMP', 'Computers', 'SEG-H', 'Consumer', 'PC-TAB', 'Tablets', 2019, 'Wi-Fi 6', 1),
('SKU-131', 'Monitor Arm Dual v2', 'MOD-841-80', 'EA', 'IT', 'Information Technology', 'STR', 'Storage', 'SEG-E', 'Enterprise', 'PC-AUDIO', 'Personal Audio Devices', 2023, 'QLED', 1),
('SKU-132', 'Cable Management Kit v2', 'TYP-242-24', 'PAIR', 'SPT', 'Sports & Outdoors', 'PWR', 'Power', 'SEG-F', 'Budget', 'PC-HUB', 'Hubs & Docking Stations', 2019, 'HDMI 2.1', 1),
('SKU-133', 'USB 3.2 Hub 7-Port v2', 'MDL-774-91', 'PAIR', 'HOM', 'Home Appliances', 'COMP', 'Computers', 'SEG-G', 'Professional', 'PC-PRT', 'Printers & Scanners', 2019, 'Thunderbolt 4', 1),
('SKU-134', 'Streaming Microphone v2', 'MDL-406-52', 'EA', 'OFF', 'Office Supplies', 'CAM', 'Cameras', 'SEG-F', 'Budget', 'PC-TV', 'Television & Displays', 2019, '5G NR', 1),
('SKU-135', 'Ring Light 18" v2', 'TYP-883-61', 'EA', 'IT', 'Information Technology', 'CONN', 'Connectivity', 'SEG-E', 'Enterprise', 'PC-LAPTOP', 'Portable Computers', 2019, 'MediaTek Dimensity', 1),
('SKU-136', 'Green Screen Kit v2', 'SKU-717-65', 'EA', 'SPT', 'Sports & Outdoors', 'PWR', 'Power', 'SEG-A', 'Premium', 'PC-SSD', 'Solid State Drives', 2024, 'NVMe PCIe 4.0', 1),
('SKU-137', 'Studio Monitor Speakers v2', 'MOD-358-73', 'PAIR', 'ACC', 'Accessories', 'COMP', 'Computers', 'SEG-B', 'Mid-Range', 'PC-LAPTOP', 'Portable Computers', 2020, 'LTE Cat-20', 1),
('SKU-138', 'Thunderbolt 4 Cable v2', 'SKU-110-82', 'PAIR', 'ACC', 'Accessories', 'NET', 'Networking', 'SEG-G', 'Professional', 'PC-CPU', 'Processors', 2023, 'ARM Cortex', 1),
('SKU-139', 'HDMI 2.1 Cable 3m v2', 'MDL-264-28', 'EA', 'OFF', 'Office Supplies', 'NET', 'Networking', 'SEG-D', 'Peripherals', 'PC-HUB', 'Hubs & Docking Stations', 2020, 'USB-C PD', 1),
('SKU-140', 'DisplayPort Cable 1.4 v2', 'SER-874-49', 'BOX', 'CE', 'Consumer Electronics', 'AUD', 'Audio', 'SEG-F', 'Budget', 'PC-AUDIO', 'Personal Audio Devices', 2022, 'Bluetooth 5.0', 1),
('SKU-141', 'Ethernet Cable Cat8 v2', 'PRD-728-88', 'PAIR', 'IT', 'Information Technology', 'DISP', 'Displays', 'SEG-F', 'Budget', 'PC-PRT', 'Printers & Scanners', 2022, 'AMD Ryzen 9', 1),
('SKU-142', 'Smart Home Hub v2', 'MDL-205-20', 'PK', 'IND', 'Industrial Equipment', 'PWR', 'Power', 'SEG-C', 'Gaming', 'PC-MON', 'Monitors', 2018, 'RISC-V', 1),
('SKU-143', 'Smart Plug 4-Pack v2', 'MOD-319-35', 'PK', 'IT', 'Information Technology', 'CAM', 'Cameras', 'SEG-H', 'Consumer', 'PC-CPU', 'Processors', 2020, 'OLED', 1),
('SKU-144', 'IP Camera Outdoor v2', 'PRD-559-20', 'PK', 'HOM', 'Home Appliances', 'VID', 'Video', 'SEG-C', 'Gaming', 'PC-TAB', 'Tablets', 2024, 'Snapdragon 8 Gen 2', 1),
('SKU-145', 'Video Doorbell Pro v2', 'MDL-334-64', 'PAIR', 'IT', 'Information Technology', 'CAM', 'Cameras', 'SEG-B', 'Mid-Range', 'PC-RAM', 'Memory Modules', 2020, 'NVMe PCIe 4.0', 1),
('SKU-146', 'Smart Thermostat v2', 'MOD-725-31', 'SET', 'IND', 'Industrial Equipment', 'STR', 'Storage', 'SEG-H', 'Consumer', 'PC-MOB', 'Smartphones', 2018, '5G NR', 0),
('SKU-147', 'Air Purifier HEPA v2', 'PRD-799-79', 'BOX', 'HOM', 'Home Appliances', 'COMP', 'Computers', 'SEG-G', 'Professional', 'PC-CAM', 'Digital Cameras', 2018, 'ARM Cortex', 1),
('SKU-148', 'Robot Vacuum Pro v2', 'MDL-356-25', 'PAIR', 'OFF', 'Office Supplies', 'INP', 'Input Devices', 'SEG-D', 'Peripherals', 'PC-MOB', 'Smartphones', 2020, 'QLED', 1),
('SKU-149', 'Smart Light Bulb Pack v2', 'SKU-128-50', 'EA', 'IND', 'Industrial Equipment', 'PRINT', 'Printers', 'SEG-H', 'Consumer', 'PC-RAM', 'Memory Modules', 2019, 'Apple M2', 1),
('SKU-150', 'Wireless Charging Pad v2', 'TYP-159-41', 'SET', 'IT', 'Information Technology', 'NET', 'Networking', 'SEG-H', 'Consumer', 'PC-KB', 'Keyboards & Mice', 2019, 'DDR5', 1),
('SKU-151', 'MagSafe Car Mount v2', 'SER-694-43', 'BOX', 'OFF', 'Office Supplies', 'MOB', 'Mobile Devices', 'SEG-D', 'Peripherals', 'PC-SSD', 'Solid State Drives', 2022, 'Apple M2', 1),
('SKU-152', 'Phone Stand Adjustable v2', 'SKU-495-75', 'PK', 'IND', 'Industrial Equipment', 'CAM', 'Cameras', 'SEG-A', 'Premium', 'PC-RAM', 'Memory Modules', 2019, 'Mini LED', 1),
('SKU-153', 'Screen Protector Premium v2', 'SKU-782-55', 'BOX', 'MED', 'Medical Devices', 'COMP', 'Computers', 'SEG-C', 'Gaming', 'PC-SSD', 'Solid State Drives', 2018, 'Thunderbolt 4', 1),
('SKU-154', 'Laptop Sleeve 15" v2', 'TYP-726-68', 'PK', 'HOM', 'Home Appliances', 'MOB', 'Mobile Devices', 'SEG-D', 'Peripherals', 'PC-KB', 'Keyboards & Mice', 2020, '5G NR', 1),
('SKU-155', 'Backpack Tech 30L v2', 'MDL-431-54', 'PAIR', 'ACC', 'Accessories', 'PRINT', 'Printers', 'SEG-A', 'Premium', 'PC-AUDIO', 'Personal Audio Devices', 2024, '5G NR', 1),
('SKU-156', 'Cable Organizer Bag v2', 'PRD-547-91', 'PK', 'SPT', 'Sports & Outdoors', 'AUD', 'Audio', 'SEG-H', 'Consumer', 'PC-AUDIO', 'Personal Audio Devices', 2019, 'LTE Cat-20', 1),
('SKU-157', 'Travel Adapter Universal v2', 'MOD-696-72', 'BOX', 'OFF', 'Office Supplies', 'AUD', 'Audio', 'SEG-F', 'Budget', 'PC-TV', 'Television & Displays', 2020, 'Apple M2', 1),
('SKU-158', 'Gaming Chair Ergonomic v2', 'MOD-747-83', 'EA', 'MED', 'Medical Devices', 'COMP', 'Computers', 'SEG-F', 'Budget', 'PC-MON', 'Monitors', 2020, 'ARM Cortex', 1),
('SKU-159', 'Monitor Riser Bamboo v2', 'TYP-848-73', 'BOX', 'HOM', 'Home Appliances', 'INP', 'Input Devices', 'SEG-G', 'Professional', 'PC-MON', 'Monitors', 2021, 'HDMI 2.1', 1),
('SKU-160', 'Desk Mat XL v2', 'MOD-583-41', 'BOX', 'IT', 'Information Technology', 'MOB', 'Mobile Devices', 'SEG-E', 'Enterprise', 'PC-MON', 'Monitors', 2023, 'OLED', 1),
('SKU-161', 'Wrist Rest Gel v2', 'TYP-767-81', 'EA', 'MED', 'Medical Devices', 'AUD', 'Audio', 'SEG-D', 'Peripherals', 'PC-LAPTOP', 'Portable Computers', 2019, 'NVMe PCIe 4.0', 1),
('SKU-162', 'Portable Projector 1080p v2', 'MDL-485-14', 'PAIR', 'SPT', 'Sports & Outdoors', 'PWR', 'Power', 'SEG-E', 'Enterprise', 'PC-HUB', 'Hubs & Docking Stations', 2019, 'Wi-Fi 6E', 0),
('SKU-163', 'Document Scanner Portable v2', 'TYP-153-77', 'EA', 'CE', 'Consumer Electronics', 'CONN', 'Connectivity', 'SEG-E', 'Enterprise', 'PC-PRT', 'Printers & Scanners', 2018, 'OLED', 1),
('SKU-164', 'Label Printer Wireless v2', 'SER-793-97', 'BOX', 'CE', 'Consumer Electronics', 'VID', 'Video', 'SEG-B', 'Mid-Range', 'PC-HDD', 'Hard Disk Drives', 2020, 'Wi-Fi 6E', 1),
('SKU-165', 'Barcode Scanner USB v2', 'SKU-105-94', 'SET', 'MED', 'Medical Devices', 'NET', 'Networking', 'SEG-F', 'Budget', 'PC-HDD', 'Hard Disk Drives', 2024, 'PoE+', 1),
('SKU-166', 'Drawing Tablet A4 v2', 'SKU-425-26', 'PAIR', 'CE', 'Consumer Electronics', 'CONN', 'Connectivity', 'SEG-B', 'Mid-Range', 'PC-HUB', 'Hubs & Docking Stations', 2020, '5G NR', 1),
('SKU-167', 'Stylus Pen Active v2', 'PRD-547-11', 'BOX', 'SPT', 'Sports & Outdoors', 'CAM', 'Cameras', 'SEG-B', 'Mid-Range', 'PC-RAM', 'Memory Modules', 2020, 'Bluetooth 5.0', 1),
('SKU-168', 'VR Headset Standalone v2', 'PRD-473-48', 'BOX', 'MED', 'Medical Devices', 'CONN', 'Connectivity', 'SEG-C', 'Gaming', 'PC-KB', 'Keyboards & Mice', 2019, 'PoE+', 1),
('SKU-169', 'Smart Glasses AR v2', 'SKU-277-97', 'PAIR', 'MED', 'Medical Devices', 'PWR', 'Power', 'SEG-F', 'Budget', 'PC-CAM', 'Digital Cameras', 2024, 'PoE+', 0),
('SKU-170', 'Fitness Tracker Pro v2', 'SKU-566-97', 'PAIR', 'CE', 'Consumer Electronics', 'DISP', 'Displays', 'SEG-H', 'Consumer', 'PC-CAM', 'Digital Cameras', 2018, 'USB 3.2', 1),
('SKU-171', 'Smartwatch Series 5 v2', 'MDL-707-93', 'BOX', 'HOM', 'Home Appliances', 'DISP', 'Displays', 'SEG-E', 'Enterprise', 'PC-CPU', 'Processors', 2024, 'Snapdragon 8 Gen 2', 1),
('SKU-172', 'Blood Pressure Monitor v2', 'SKU-429-70', 'PAIR', 'MED', 'Medical Devices', 'DISP', 'Displays', 'SEG-D', 'Peripherals', 'PC-SSD', 'Solid State Drives', 2018, 'Thunderbolt 4', 1),
('SKU-173', 'Digital Thermometer v2', 'SER-102-53', 'PK', 'OFF', 'Office Supplies', 'CONN', 'Connectivity', 'SEG-A', 'Premium', 'PC-TAB', 'Tablets', 2019, 'Thunderbolt 4', 1),
('SKU-174', 'Mini PC Intel NUC v2', 'MOD-105-65', 'SET', 'CE', 'Consumer Electronics', 'INP', 'Input Devices', 'SEG-H', 'Consumer', 'PC-MOB', 'Smartphones', 2021, 'LTE Cat-20', 1),
('SKU-175', 'Raspberry Pi 4 Kit v2', 'MDL-280-28', 'PAIR', 'SPT', 'Sports & Outdoors', 'DISP', 'Displays', 'SEG-C', 'Gaming', 'PC-RAM', 'Memory Modules', 2021, 'Wi-Fi 6E', 1),
('SKU-176', 'Arduino Starter Kit v2', 'MDL-669-89', 'EA', 'SPT', 'Sports & Outdoors', 'CAM', 'Cameras', 'SEG-A', 'Premium', 'PC-KB', 'Keyboards & Mice', 2020, 'ARM Cortex', 1),
('SKU-177', 'Soldering Station Digital v2', 'SER-998-30', 'PAIR', 'CE', 'Consumer Electronics', 'CONN', 'Connectivity', 'SEG-A', 'Premium', 'PC-GPU', 'Graphics Cards', 2022, '5G NR', 1),
('SKU-178', 'Oscilloscope Digital 2ch v2', 'SER-205-61', 'PK', 'CE', 'Consumer Electronics', 'PWR', 'Power', 'SEG-D', 'Peripherals', 'PC-GPU', 'Graphics Cards', 2024, 'RISC-V', 1),
('SKU-179', 'Bench Power Supply v2', 'SKU-190-83', 'EA', 'ACC', 'Accessories', 'VID', 'Video', 'SEG-B', 'Mid-Range', 'PC-CPU', 'Processors', 2018, 'PoE+', 1),
('SKU-180', 'Component Tester v2', 'MDL-623-44', 'PK', 'SPT', 'Sports & Outdoors', 'DISP', 'Displays', 'SEG-G', 'Professional', 'PC-CAM', 'Digital Cameras', 2021, 'OLED', 1),
('SKU-181', 'PCB Holder v2', 'TYP-329-74', 'PK', 'CE', 'Consumer Electronics', 'VID', 'Video', 'SEG-F', 'Budget', 'PC-SSD', 'Solid State Drives', 2020, 'Intel Core i9', 1),
('SKU-182', 'Server Rack Cabinet 12U v2', 'TYP-701-54', 'PAIR', 'ACC', 'Accessories', 'INP', 'Input Devices', 'SEG-H', 'Consumer', 'PC-KB', 'Keyboards & Mice', 2024, 'OLED', 1),
('SKU-183', 'KVM Switch 4-Port v2', 'PRD-647-74', 'BOX', 'IND', 'Industrial Equipment', 'STR', 'Storage', 'SEG-D', 'Peripherals', 'PC-HDD', 'Hard Disk Drives', 2020, 'NVMe PCIe 4.0', 0),
('SKU-184', 'UPS Battery Backup v2', 'TYP-448-72', 'PK', 'SPT', 'Sports & Outdoors', 'CAM', 'Cameras', 'SEG-C', 'Gaming', 'PC-KB', 'Keyboards & Mice', 2019, 'LTE Cat-20', 0),
('SKU-185', 'Rackmount PDU v2', 'MDL-563-50', 'BOX', 'MED', 'Medical Devices', 'AUD', 'Audio', 'SEG-G', 'Professional', 'PC-AUDIO', 'Personal Audio Devices', 2018, 'Mini LED', 1),
('SKU-186', 'Fiber Patch Cable SM v2', 'PRD-815-74', 'EA', 'ACC', 'Accessories', 'CAM', 'Cameras', 'SEG-B', 'Mid-Range', 'PC-CPU', 'Processors', 2021, 'Wi-Fi 6', 0),
('SKU-187', 'SFP+ Transceiver Module v2', 'SKU-943-96', 'BOX', 'ACC', 'Accessories', 'STR', 'Storage', 'SEG-G', 'Professional', 'PC-MON', 'Monitors', 2023, 'NVMe PCIe 4.0', 1),
('SKU-188', 'PoE Injector 30W v2', 'TYP-437-76', 'EA', 'OFF', 'Office Supplies', 'INP', 'Input Devices', 'SEG-A', 'Premium', 'PC-TV', 'Television & Displays', 2021, 'HDMI 2.1', 1),
('SKU-189', 'Managed Switch 48-Port v2', 'PRD-413-60', 'BOX', 'ACC', 'Accessories', 'CONN', 'Connectivity', 'SEG-G', 'Professional', 'PC-PRT', 'Printers & Scanners', 2024, 'ARM Cortex', 1),
('SKU-190', 'Thermal Camera Handheld v2', 'PRD-341-88', 'PAIR', 'IND', 'Industrial Equipment', 'AUD', 'Audio', 'SEG-A', 'Premium', 'PC-SSD', 'Solid State Drives', 2018, 'OLED', 1),
('SKU-191', 'Endoscope Camera v2', 'MDL-720-40', 'SET', 'MED', 'Medical Devices', 'PRINT', 'Printers', 'SEG-E', 'Enterprise', 'PC-GPU', 'Graphics Cards', 2023, '5G NR', 0),
('SKU-192', 'Digital Microscope USB v2', 'MDL-639-71', 'PAIR', 'IND', 'Industrial Equipment', 'AUD', 'Audio', 'SEG-E', 'Enterprise', 'PC-CPU', 'Processors', 2024, 'USB 3.2', 1),
('SKU-193', 'Caliper Digital 6" v2', 'SKU-899-75', 'PK', 'MED', 'Medical Devices', 'VID', 'Video', 'SEG-A', 'Premium', 'PC-CPU', 'Processors', 2024, 'Mini LED', 1),
('SKU-194', 'Label Maker Pro v2', 'MDL-653-14', 'EA', 'SPT', 'Sports & Outdoors', 'MOB', 'Mobile Devices', 'SEG-G', 'Professional', 'PC-LAPTOP', 'Portable Computers', 2023, 'Bluetooth 5.0', 0),
('SKU-195', 'Laminator A3 v2', 'SER-968-26', 'SET', 'MED', 'Medical Devices', 'PRINT', 'Printers', 'SEG-G', 'Professional', 'PC-MON', 'Monitors', 2022, 'DDR5', 1),
('SKU-196', 'Paper Shredder 12-Sheet v2', 'MDL-593-19', 'EA', 'SPT', 'Sports & Outdoors', 'PRINT', 'Printers', 'SEG-B', 'Mid-Range', 'PC-MON', 'Monitors', 2021, 'AMD Ryzen 9', 1),
('SKU-197', 'Electric Stapler v2', 'MDL-398-32', 'PAIR', 'MED', 'Medical Devices', 'INP', 'Input Devices', 'SEG-F', 'Budget', 'PC-TAB', 'Tablets', 2019, 'USB 3.2', 1),
('SKU-198', 'Wireless Bluetooth Headphones v3', 'SKU-498-63', 'PK', 'MED', 'Medical Devices', 'PWR', 'Power', 'SEG-H', 'Consumer', 'PC-RAM', 'Memory Modules', 2018, 'DDR5', 0),
('SKU-199', 'Smart LED TV 55" v3', 'PRD-751-48', 'PAIR', 'MED', 'Medical Devices', 'COMP', 'Computers', 'SEG-H', 'Consumer', 'PC-RAM', 'Memory Modules', 2020, 'OLED', 1),
('SKU-200', 'Gaming Laptop Pro v3', 'PRD-512-58', 'SET', 'CE', 'Consumer Electronics', 'AUD', 'Audio', 'SEG-C', 'Gaming', 'PC-TV', 'Television & Displays', 2019, 'RISC-V', 1);